name: Rely
description: We'll be there for you...

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1



environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^5.0.2
  firebase_database: 3.0.6
  firebase_storage: ^3.0.3
  
  google_sign_in: ^3.2.4

  flutter_facebook_login: ^1.2.0

  http: ^0.12.0+2 
  flutter_launcher_icons: "^0.7.0"
  material_design_icons_flutter: 3.4.4795
  shared_preferences: ^0.5.4+8
  intro_slider: ^1.0.8
  flutter_country_picker: ^0.1.6
  fluttertoast: ^3.1.3
  cupertino_icons: ^0.1.2
  
  
  
  provider: ^3.1.0
  google_maps_flutter: ^0.5.21+13
  geolocator: ^5.1.5  
  stack_trace: ^1.9.3  
  android_intent: ^0.3.4+7


  image_picker_modern: ^0.4.12
  image_cropper: ^1.0.1
  flutter_image_compress: ^0.6.3


  device_id: ^0.2.0


  upi_india: 1.1.1


  calendarro: ^1.1.2
  true_time: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo/round.png
    - assets/images/SignIn/background.png
    - assets/images/Intro/Slide1.png
    - assets/images/Intro/Slide2.png
    - assets/images/Intro/Slide3.png
    - assets/images/ProfilePicture/default.png
    - assets/images/Splashscreen/Splashscreen.png
    - assets/images/Payment/GooglePay.png
    - assets/images/Payment/PhonePe.png
    - assets/images/Payment/BHIM.png
    
  fonts:
    - family: Standard
      fonts:
        - asset: assets/fonts/Standard.ttf
    - family: Handwritten
      fonts:
        - asset: assets/fonts/Handwritten.ttf
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  ios: true
  android: true
  #image_path: "assets/launcher/icon.png"
  image_path_ios: "assets/images/logo/icon.png"
  image_path_android: "assets/images/logo/icon.png"
  adaptive_icon_background: "assets/images/logo/background.png"
  adaptive_icon_foreground: "assets/images/logo/foreground.png"